[platformio]
default_envs = stream_to_pc

[env]
platform = atmelmegaavr
board = nano_every
framework = arduino
monitor_speed = 115200

[env:calibration]
build_src_filter =
    -<*>
    +<apps/calibration.cpp>

[env:stream_to_pc]
build_src_filter =
    -<*>
    +<apps/stream_to_pc.cpp>
